# Generated by Django 4.1.6 on 2023-02-10 01:46

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=False)),
                ('isadmin', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profilepicture', models.URLField(default='https://cdn.pixabay.com/photo/2017/11/10/05/48/user-2935527_960_720.png', max_length=300)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.CharField(default='AA', max_length=250)),
                ('postdate', models.DateTimeField()),
                ('impressions', models.CharField(blank=True, max_length=250)),
                ('thumbnail', models.URLField()),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('channel', models.CharField(max_length=150)),
                ('keyword', models.CharField(default='youtubevideo', max_length=200)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtubepostings', to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateTimeField(default=datetime.datetime.now)),
                ('impressions', models.CharField(blank=True, max_length=250)),
                ('keyword', models.CharField(default='music', max_length=200)),
                ('previewurl', models.URLField(default='https://p.scdn.co/mp3-preview/5a2b8b0d4cc595c371575a419288cd1799e3ed2c?cid=ba3f5e0f0bbb4b3e973df8367d56d100')),
                ('thumbnail', models.URLField(default='https://i.scdn.co/image/ab67616d0000b27336615a0a60523dd62135ab3a')),
                ('album', models.CharField(blank=True, max_length=250)),
                ('songtitle', models.CharField(blank=True, max_length=250)),
                ('artist', models.CharField(blank=True, max_length=250)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicpostings', to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateTimeField()),
                ('impressions', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('overview', models.CharField(blank=True, max_length=200)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('thumbnail', models.URLField()),
                ('keyword', models.CharField(default='movie', max_length=200)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviepostings', to='myapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Gossip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateTimeField()),
                ('post', models.CharField(max_length=250)),
                ('keyword', models.CharField(default='gossip', max_length=200)),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gossippostings', to='myapp.member')),
            ],
        ),
    ]
